import json
from urllib.error import URLError
from urllib.request import Request, urlopen


def generate_description(text: str) -> str | None:
    """Return a short description generated by a local Ollama model."""

    # 🔹 очистка + нормализация
    excerpt = " ".join(text.split()).strip()

    # 🔹 защита от пустого/короткого текста
    if not excerpt or len(excerpt) < 200:
        return None

    # 🔹 ограничение размера
    excerpt = excerpt[:5000]

    # 🔹 prompt (без лишних отступов)
    prompt = f"""Книга:

{excerpt}

Сделай краткое описание книги (3–5 предложений):

- о чём книга
- для кого она
- ключевые идеи

Не выдумывай факты.
Используй только информацию из текста.
Пиши кратко и по делу.
"""

    payload = json.dumps(
        {
            "model": "mistral",
            "prompt": prompt,
            "stream": False,
        }
    ).encode("utf-8")

    request = Request(
        "http://localhost:11434/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urlopen(request, timeout=60) as response:
            body = response.read().decode("utf-8")
    except (OSError, URLError, TimeoutError, ValueError):
        return None

    try:
        data = json.loads(body)
    except json.JSONDecodeError:
        return None

    result = data.get("response")
    if not result:
        return None

    # 🔹 финальная очистка
    cleaned = " ".join(str(result).split()).strip()
    return cleaned or None